config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders

  root "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  SHIPPING_METHODS = ['ems', 'courier', 'same_day'].freeze
  STATUS = ['processing'].concat(Fedex::Shipment::STATUS).freeze

  enum status: STATUS.map.with_index { |s, i| [s, i] }.to_h

  belongs_to :product

  validates :customer_name, presence: true
  validates :adress, presence: true
  validates :zip_code, presence: true
  validates :shipping_method, presence: true, inclusion: { in: SHIPPING_METHODS }
  validates :product, presence: true

  after_create :generate_shipment
  after_create :monitor_shipment

  scope :search, ->(query) do
    joins(:product).where('LOWER(customer_name) LIKE :query OR LOWER(adress) LIKE :query OR LOWER(zip_code) LIKE :query OR LOWER(shipping_method) LIKE :query OR LOWER(products.name) LIKE :query', query: "%#{query.downcase}%")
  end

  delegate :name, to: :product, prefix: true

  # Generate shipment for the order
  def generate_shipment
    FedexService.new(order: self).call
  end

  def monitor_shipment
    UpdateShippingStatusJob.perform_later(self)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/crud_controller.rb
# frozen_string_literal: true

module CrudController
  extend ActiveSupport::Concern

  included do
    before_action :set_resource_class
    before_action :set_resource, only: [:show, :edit, :update, :manage_details]
  end

  def index
    order = params[:order].present? ? params[:order].to_s : "updated_at"
    sort  = params[:sort].present? ? params[:sort].to_s : "desc"

    @resources = @resource_class.all.order(:created_at))
    # @resources = @resources.unscope(:order).order("#{order} #{sort}") if params[:order].present?
  end

  def show; end

  def new
    @resource = resource_class.new
  end

  def edit;  end

  def create
    @resource = resource_class.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'The item was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'The item was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'The item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def resource_class
    controller_path.classify.delete_prefix("Backoffice::").constantize
  end

  def set_resource_class
    @resource_class = resource_class
  end

  def set_resource
    @resource = @resource_class.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # be sure to replace instance variables in views by @resource
  # be sure to define resource_params method in private
  # enable includer and remove everything else
  # if you want to use the search feature within the index method, just redefine the method here
  # include CrudController

  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.includes(:product)
    @orders = @orders.search(params[:search].to_s) if params[:search].present?
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    product_id = params[:product_id].presence || nil

    @order = Order.new(product_id: product_id)
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:product_id, :customer_name, :adress, :zip_code, :shipping_method, :status)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price, :stock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcnCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Products', products_path %>
        <%= link_to 'Orders', orders_path %>
        <%= link_to 'New Order', new_order_path %>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.select :product_id, Product.all.pluck(:id, :name).map { |id, name| [name, id] } %>
  </div>

  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :shipping_method %><br>
    <%= f.select :shipping_method, Order::SHIPPING_METHODS.map { |name| [name, name] } %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Order <%= @order.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<div style="width: 50%; margin-top: 30px; margin-bottom: 30px; border: 1px solid gray; padding: 10px;">
  <%= form_tag orders_path, method: :get do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", name: nil %>
    </p>
  <% end %>
</div>

<%= tag.h2 "Here is your search results:" if params[:query].present? %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Customer</th>
      <th>Status</th>
      <th>Shipping Method</th>
      <th>Zipcode</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.status.capitalize %></td>
        <td><%= order.shipping_method %></td>
        <td><%= order.zip_code %></td>
        <td><%= order.product_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empty Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/orders/show.html.erb
<div id="<%= dom_id @order %>">
  <%= tag.h1 "Order ID: #{@order.id}" %>

  <pre>
    <code>
      <%= @order.inspect %>
    </code>
  </pre>
  

  <%= link_to "Home", root_path %>
  <%= link_to "All orders", orders_path %>
  <%= link_to "Edit", edit_order_path(@order) %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'New Order', new_order_path(product_id: product.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>